### ISSUE TITLE
Sandbox ortamında yaptığım istekten 2000 hatası alıyorum

### ISSUE THREAD

**Issue by kodditcom** [iyzico/iyzipay-dotnet#103]
Selamlar,

Pazaryeri entegrasyonu için .NET üzerinde gerçekleştirdiğim işlemde 2000 - Bu servis sadece pazaryeri müşterilerine açıktır hatası alıyorum.

Api Key ve Secret sandbox hesabımdan aldığım kodlar biçiminde, BaseUrl'i ise https://sandbox-api.iyzipay.com olarak gönderiyorum.

Neden böyle bir hata ile karşılaşıyorum yardımcı olabilir misiniz rica etsem?

Teşekkürler

**Comment by can3ry** [comment]
Selamlar, merchant panelde ayarlar kısmında üye işyeri  id bilgisini destek@iyzico.com adresine iletirseniz pazar yeri özelliğini aktifleştirebilirler.
Teşekkürler

**Comment by sukaraduman** [comment]
@ornitorenk  merhaba bende çok büyük hatalar alıyorum. ^3D satışı kullanamıyorum . 3D satışı kullanabildinmi ? Kullandıysan bana ulaşır mısın rica etsem 0555 034 12 83

**Comment by ShopskaSalad** [comment]
> @ornitorenk merhaba bende çok büyük hatalar alıyorum. ^3D satışı kullanamıyorum . 3D satışı kullanabildinmi ? Kullandıysan bana ulaşır mısın rica etsem 0555 034 12 83 whatsaptan bekliyorum. Saygılar

Hey there,

Even though this not related to given issue.
Let me explain you our 3DS services.

So let’s get started!
Basically, there are 2(two) main steps at 3DS process, respectively;
 
- Step 1 - Init request; https://dev.iyzipay.com/en/api/auth-with-3d#1request
- Step 2 - Auth request; https://dev.iyzipay.com/en/api/auth-with-3d#2request

## Step 1;
 
Here you have to send your API request to given URL path which is https://sandbox-api.iyzipay.com/payment/3dsecure/initialize for sandbox and https://api.iyzipay.com/payment/3dsecure/initialize for prod env.
With mandatory parameters can be found on the link https://dev.iyzipay.com/en/api/auth-with-3d#1request.
Please do not miss to add callbackUrl to your request, a friendly advice would be https://webhook.site/ 
 
Obviously, you will have a response with given parameters on the link https://dev.iyzipay.com/en/api/auth-with-3d#1response.
Quick summarize, threeDSHtmlContent is base64 crypted html page where your end-user expected to validate 3DS page OTP verification.
 
An example of decoded threeDSHtmlContent;
![image](https://user-images.githubusercontent.com/13609808/102089418-3a730900-3e2d-11eb-8fa5-433fc8ecaf60.png)

An example of decoded threeDSHtmlContent interface on the browser;
![image](https://user-images.githubusercontent.com/13609808/102089442-419a1700-3e2d-11eb-96b5-c1ac810fc29f.png)
So overall, either in the response at your callbackUrl mdStatus will be 1-Success or mdStatus – others; https://dev.iyzipay.com/en/api/auth-with-3d#mdstatus.

##Step 2;
 
In this step we assume that you have seen a response with mdStatus 1 at your callbackUrl. Now simply It is time to make your transaction official between Acquirer and Issuer.
Please send your API request to given URL path which is https://sandbox-api.iyzipay.com/payment/3dsecure/auth for sandbox test env.
With mandatory parameters can be found on the link https://dev.iyzipay.com/en/api/auth-with-3d#2request.
You may get your paymentId from Step1’s response.
 
So if you have a response from the latest request, you have finished 3DS payment operation on iyzico sandbox env in 2(two) steps!
 
Additionally, you may find test cards from https://dev.iyzipay.com/en/api/auth-with-3d#testcards and I am attaching mentioned request Postman collections to mail as well.
 
Please reach us if we can help you further.

**Comment by ShopskaSalad** [comment]
The issue has closed as there are no further updates.

**Comment by yilmazemrepala** [comment]
Ben subMerchant oluşturma işleminde bu hatayı aldım. İyzico desteği aradım ve sorunumu 5 dakika içinde çözdüler.
