### ISSUE TITLE
Sandbox hesabıyla Ödeme İşlemleri İşlerken Hata Kodu 11 Alınıyor

### ISSUE THREAD

**Issue by atiol** [iyzico/iyzipay-dotnet#109]
Merhaba,
Dil ayarı olarak "tr" ile ödeme yapmaya çalıştığımda, "mesaj: Geçersiz istek" ve "hata grubu: null" ile "hata kodu: 11" alıyorum. "en" olarak değiştirdiğimde işlem başarıyla işleniyor.
Ne yazık ki, yukarıdaki hata dokümantasyonda hata kodlarının altında listelenmiyor, bu yüzden ne anlama geldiğine dair hiçbir fikrim yok, yardımcı olabilirseniz sevinirim.
Şimdiden teşekkürler.

**Comment by shuetisha** [comment]
Selam @atiol ,

Hatayı tekrardan oluşturabilmem için, hangi sample üzerinde hatayı aldığını ve yaptığın değişiklikleri benimle paylaşabilir misin?

**Comment by atiol** [comment]
Merhaba @shuetisha ,
Hatayı düzeltebildim sağol ilgin için. `PaidPrice` ve `Price` property'leri `double` tipinden `string` tipine çevirdiğimde `cultureinfo` duyarlı olarak çevriliyor örneğin locale `tr` için: `PaidPrice ve Price = 27.25` -> toString() -> `"27,25"` oluyor, o yüzden `Error code: 11` ve `message: "Geçersiz istek"` alıyorum.
