### ISSUE TITLE
3Dsiz ödemede instance almada exceptiona düşme

### ISSUE THREAD

**Issue by elemenro** [iyzico/iyzipay-dotnet#110]
3dsiz ödeme için 
` CreatePaymentRequest request = new CreatePaymentRequest();` 
başta aldığım instance da bazı ödemelerde "Object reference not set to an instance of an object." alıyorum.Diğer ödemelerin çoğunda başarılı olarak geçiyor...

**Comment by ShopskaSalad** [comment]
Selamlar. 
Burada bulunan senaryolardan birine takılmadığına emin olduktan sonra, https://stackoverflow.com/questions/779091/what-does-object-reference-not-set-to-an-instance-of-an-object-mean.
Kod örneği paylaşabilirseniz inceleyelim.
Kolaylıklar

**Comment by ShopskaSalad** [comment]
Issue, cevap alınamadığı için kapatılmıştır.
