### ISSUE TITLE
Iyzipay.Model.V2.Subscription.PaymentInterval eksik enum değerleri

### ISSUE THREAD

**Issue by velikayikci** [iyzico/iyzipay-dotnet#133]
Iyzipay.Model.V2.Subscription namespace altındaki PaymentInterval enumunda sadece 2 değer var haftalık ve aylık,
Yıllık ve diğerleri yok.

**Comment by byasarcse** [comment]
Merhabalar @velikayikci,

İlgili enum değerleri eklenmiştir. 
https://github.com/iyzico/iyzipay-dotnet/pull/134
