### ISSUE TITLE
Format Price hatası

### ISSUE THREAD

**Issue by CanerLenger** [iyzico/iyzipay-dotnet#32]
RequestFormatter içinde FormatPrice metodunda parametre olarak örn:35.5 gönderilince sonuna .0 ekliyor ilk baştaki kontrol sebebi ile. Bu nedenle de Request "Geçersiz imza" hatası alıyor.

if (!price.ToString().Contains(","))
{
                return price + ".0";
}

**Comment by sotuzun** [comment]
Client'a fiyat bilgisi olarak noktalı yollamanız gerekir. Virgüllü yollarsanız hata alırsınız. Bu yüzden fiyat bilgisinde client kullanırken noktalı yollamanız gerekir.
