### ISSUE TITLE
2.0.0'dan 2.1.2'ye update sorunu

### ISSUE THREAD

**Issue by hgunay** [iyzico/iyzipay-dotnet#53]
Guncelleme yaparken references'tan dll'i kaldiriyor ancak yerine yeni dll'i vermiyor. Packages altinda guncel versiyonu gorebiliyorum.
Framework 4.5.2
Json 9.0.1

**Comment by sotuzun** [comment]
Sorunlu olduğu için 2.1.0, 2.1.1, 2.1.2 versiyonlarını kaldırdık. 2.1.3 versiyonu sorunsuz bir şekilde indirilebilir.
