### ISSUE TITLE
Retrieve Pending Approval Request List ?

### ISSUE THREAD

**Issue by CanerLenger** [iyzico/iyzipay-dotnet#56]
I want to query all payments (pendingApproval,approved,disapproved etc.) in a specific time interval like on the iyzico merchant panel. I couldn't find any method related with this subject in iyzipayClient.

The reason why i ask this, i have to see all the pending approval transactions made by Alo-tech. 
It is really hard to find Alo Tech's requests merchant panel, I want to approve those payments on my admin panel instead of Iyzico Merchant Panel.

Thanks.

**Comment by sotuzun** [comment]
Sounds reasonable. I am adding to our backlog.
