### ISSUE TITLE
CreateCheckoutFormInitializeRequest Decimal Seperator

### ISSUE THREAD

**Issue by onuromer** [iyzico/iyzipay-dotnet#62]
Selam arkadaşlar,

CreateCheckoutFormInitializeRequest içerisinde PaidPrice veya Price için Türkçe ondalık ayracı olan virgül ile ondalık bir değer yolladığımızda "geçersiz istek" hatası alıyoruz. 

Bu durumun Locale farklılığından ötürü olduğunu tespit ettik. Varsayılan nokta ayraç kullanıldığında sorun yok.

Mevcut durumda aynı request içerisinde "locale" adında bir parametre de gönderiliyor. Dokümantasyonunuzdan okuduğum kadarıyla da bu parametre "istek sonucunda dönen metinlerin dilini ayarlamak için" kullanılıyor, yani genel olarak kültürü belirlemiyor. 

Ancak belirlerse daha güzel olabilir. Böylece biz de nokta mı virgül mü gereksiz kasmak zorunda kalmayız:
`request.PaidPrice =ShoppingCart.GrandTotal.ToString(new NumberFormatInfo() {NumberDecimalSeparator="." });`

Öneridir.

Teşekkürler
Onur

**Comment by sotuzun** [comment]
Merhaba,
Fiyat bilgisi yollarken decimal değeri noktalı şekilde yollamanız gerekiyor. Bütün para birimleri için fiyat formatımız bu şekilde. Client'ta bir soruna yol açmamak için gönderilen değere dokunmuyoruz. İstenilen ise noktalı bir şekilde gönderilmesi.
