### ISSUE TITLE
CheckoutForm PaymentStatus Enum'u yok

### ISSUE THREAD

**Issue by onuromer** [iyzico/iyzipay-dotnet#63]
Selam Arkadaşlar,

Model altında PaymentStatus enum değerleri mevcut değil. Dokümantasyonunuzdan gördüğüm kadarıyla olası değerler şöyle: 
SUCCESS, FAILURE, INIT_THREEDS, CALLBACK_THREEDS, BKM_POS_SELECTED, CALLBACK_PECCO

Bu değerler güncel mi?

Enum olarak eklerseniz süper makbule geçer. Keza bizler de kendi kodlarımızda hard coded kullanmak zorunda kalmayız, güncelliğinden de emin oluruz.

Bilginize, Teşekkürler
Onur

**Comment by sotuzun** [comment]
Merhaba,
Contribution yapabilirseniz seviniriz.

**Comment by onuromer** [comment]
Contribution yapalım elbette tabii. Contribution yaparız ama para ile hizmet alınan bir firmanın kütüphanesine de (hele ki bu kadar basit ve saçma bir eksik için) müşterileriniz olarak bizlerin "contribution" yapmasını saçma bulduğumu paylaşmak isterim.

Bu opensource veya sosyal bir proje değil. Bu iş berbere gidip berberin de size tam ücret çekip "-Ya makas orda işte at iki kesik sen de caaanımm" demesinden farksız kanımca. 

Darılmaca gücenmece yok: özetle o contribution'ı siz yapmalısınız.

**Comment by ShopskaSalad** [comment]
Selamlar,
Ödemenizin durumunu öğrenmek için ekte verilenhttps://dev.iyzipay.com/tr/odeme-formu/odeme-formu-sonucu mdStatus kontrolü yeterlidir. 1 olmayan tüm durumlarda ödeme alınamamış demektir.
Kolaylıklar

**Comment by onuromer** [comment]
> 
> 
> Selamlar,
> Ödemenizin durumunu öğrenmek için ekte verilen https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-sonucu mdStatus kontrolü yeterlidir. 1 olmayan tüm durumlarda ödeme alınamamış demektir.
> Kolaylıklar

Bunun ne alakası var PaymentStatus Enum'unun iyzipay kütüphanesinde olmamasıyla? PaymentStatus enum'u yok denilmiş, nereden ödemenin durumu öğrenilebilir diye sorulmuyor. Bu bi soru da değildi ki zaten. Tespitti.

Bu arada ilettiğiniz bilgi de hatalı @ShopskaSalad. Okudunuz mu bilmiyorum ama dokümantasyonda yazana göre "ödeme başarısız ve 3DS ile yapılmadıysa" böyle bir değer de dönmüyor: (ancak 3DS koşuluyla bu dönüyormuş) 

![grafik](https://user-images.githubusercontent.com/2822720/102088859-c3814480-3e1b-11eb-92b8-f15fb2e2a62c.png)

**Comment by ShopskaSalad** [comment]
> > Selamlar,
> > Ödemenizin durumunu öğrenmek için ekte verilen https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-sonucu mdStatus kontrolü yeterlidir. 1 olmayan tüm durumlarda ödeme alınamamış demektir.
> > Kolaylıklar
> 
> Bunun ne alakası var PaymentStatus Enum'unun iyzipay kütüphanesinde olmamasıyla? PaymentStatus enum'u yok denilmiş, nereden ödemenin durumu öğrenilebilir diye sorulmuyor. Bu bi soru da değildi ki zaten. Tespitti.
> 
> Bu arada ilettiğiniz bilgi de hatalı @ShopskaSalad. Okudunuz mu bilmiyorum ama dokümantasyonda yazana göre "ödeme başarısız ve 3DS ile yapılmadıysa" böyle bir değer de dönmüyor: (ancak 3DS koşuluyla bu dönüyormuş)
> 
> ![grafik](https://user-images.githubusercontent.com/2822720/102088859-c3814480-3e1b-11eb-92b8-f15fb2e2a62c.png)

Tespitiniz için teşekkürler @onuromer. 
Bu tespitinizi, ilgili ekiplere bildiriyor olacağım. 

Son olarak, https://github.com/iyzico/iyzipay-dotnet/issues/63#issuecomment-744397511 3DS örneği tespitinizden ayrı olarak tespitiniz etrafında oluşabilecek sorular için bir çözüm önerisi olarak yazılmıştır ve hata içermemektedir, ancak eklediğiniz açıklama için de ayrıca teşekkür ederiz.

**Comment by byasarcse** [comment]
Merhabalar,

PaymentStatus parametresi birden fazla değer alabilmektedir. Gelişen yeni ürünler ile birlikte, yeni ara statü değerleri eklenebilmektedir. Bu nedenle parametre string olarak yazılmıştır.

FAILURE
SUCCESS
INIT_THREEDS
CALLBACK_THREEDS
BKM_POS_SELECTED
INIT_APM
INIT_BANK_TRANSFER
INIT_CREDIT
PENDING_CREDIT
INIT_CONTACTLESS

Teşekkürler,
