### ISSUE TITLE
JSONReader Exception

### ISSUE THREAD

**Issue by farslan06** [iyzico/iyzipay-dotnet#65]
Merhabalar,
Sand-box ortamında test ederken hiçbir sorunla karşılaşmıyorum,bütün sonuçları düzgün alabiliyorum.Fakat
gerçek api ve secretkeyi girip base-url'e kendi sitemin  urlsini girdiğimde aşağı daki hatayı alıyorum base-url: options.BaseUrl = "https://www.ornek.com";

hata : 

An exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json.dll but was not handled in user code

Additional information: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by AlicanAkkus** [comment]
@farslan06 selamlar,

Options içerisinde yer alan BaseUrl adresi iyzico api'lerini temsil etmektedir. Bu nedenle canlı ortamda işlem yapmak istiyorsan BaseUrl olarak [api.iyzipay](https://api.iyzipay.com) adresini vermelisin. 

Herhangi bir problemde entegrasyon@iyzico.com adresine mail atmaktan çekinme lütfen.

iyi çalışmalar, Alican.

**Comment by farslan06** [comment]
@AlicanAkkus 

Teşekkür ederim hızlı cevabın için :)
