### ISSUE TITLE
.net core destekleyen official surumunuz var mı? 

### ISSUE THREAD

**Issue by uakdemir** [iyzico/iyzipay-dotnet#67]
.net core destekleyen official surumunuz var mı?

**Comment by sotuzun** [comment]
dotnet core desteği ile ilgili çalışmayı başlattık. En kısa sürede çalışmaları tamamlayacağız.

**Comment by onurh** [comment]
Bump. This would be a great addition to this library.

**Comment by Blind-Striker** [comment]
See #76

**Comment by serkanyazicioglu** [comment]
Konuyla ilgili official geliştirme olacak mıdır? Yoksa Armut.com nuget paketini kullanacağınız.

Eline sağlık @Blind-Striker 👍 😃

**Comment by scorpion86** [comment]
Yıl 2019

**Comment by tugberkgunver** [comment]
Merhabalar, .Net Core 3.0 ile projem iyzico ödeme formu kullanmak istiyorum. Nasıl bir yol izlemeliyim ? Çünkü .net core sürümüzü göremedim.

**Comment by fsari** [comment]
> Yıl 2019. Bir tane dotnet developer çalıştıramayacak kadar zayıf bir firma mı iyzico?

Yıl 2020 sanırım halen bir gelişme yok

**Comment by gamzegedikli** [comment]
> Merhabalar, .Net Core 3.0 ile projemde iyzico ödeme formu kullanmak istiyorum. Nasıl bir yol izlemeliyim ? Çünkü .net core sürümüzü göremedim.
> Not: Iyzipay'i denedim. Ödeme formu olarak .Net Core üzerinde çalıştırdım gibi duruyor. Fakat entity framework tarafında sıkıntı çıkarabilir.

Merhaba @tugberkgunver  aynı sorunu yaşıyorum ancak iyzico ile ödeme formunu görüntüleyemedim. .net ile açtığım başka bir projede çalışıyor ama .net core 3 üzerinden çalıştıramadım. Neyi farklı yaptığınızı açıklar mısınız?

**Comment by halitsoydemir** [comment]
v2.1.33 sürümünden itibaren core supported şekilde çalışmaktadır.
