### ISSUE TITLE
3d dönüş ekranında hata mesajları(CheckoutForm) görünmüyor

### ISSUE THREAD

**Issue by onderturhan** [iyzico/iyzipay-dotnet#69]
Merhaba,

İyzipay de hata yönetimi için “başarısız işlem testi” gerçekleştirmek istiyorum. 
Hata yönetimini sağlayabilmek için gerçek kart bilgilerini doğru olarak girdim ve kartın 3d ekranında  ‘Vazgeç’ yaparak çıktım.
Dönen değerlerde hata mesajı boş geliyor(ErrorCode,ErrorGroup,ErrorMessage).
![image](https://user-images.githubusercontent.com/10496500/33374677-2cce7ec8-d518-11e7-890b-b300cdb4990b.png)

**Comment by ShopskaSalad** [comment]
Merhaba Önder Bey,

3d ekranı bankanın kendi yazılımı olup, biz PF olarak sadece aracı durumundayız.
Benzer senaryolar tarafımıza ara ara gelmekte olup;

-Kart hamilinin tarayıcısındaki problem
-Enrollment aşamasından sonra gönderilmesi zorunlu olan pareq  requestinin işyeri tarafından gönderilmemesi
-Pareq isteğinin kart bankasına gönderilmiş olmasına rağmen kart bankasından  (pares)  cevabının alınmamış olması
-Kart hamilinin işlemi doğrulamadan SMS şifresini gireceği ekranı kapatmış olması
 
gibi birden fazla sebebe bağlı olarak gerçekleşebilir. 

Bu durumda, ilgili ödemeye ait detaylarla birlikte bizimle iletişim kurmanız halinde sizin için ilgili bankayla iletişime geçebiliriz.

Kolaylıklar

**Comment by ShopskaSalad** [comment]
Issue, cevap alınamadığı için kapatılmıştır.
