### ISSUE TITLE
ItemApproval Hata Kodu: 5067

### ISSUE THREAD

**Issue by alperensaylar** [iyzico/iyzipay-dotnet#73]
Item Approval işlemini yapmaya çalıştığımda oluşturduğum Approval objesinde 5067 kodlu "Sadece marketplace üye işyerleri ödeme kırılımı onayı verebilir" mesajlı uyarıyı veriyor. Gönderdiğim tüm verileri kontrol ediyorum, hiç bir yanlışlık yok fakat sonuç böyle oluyor. 
![ekran resmi 2018-02-07 15 24 14](https://user-images.githubusercontent.com/5227869/35916300-02237004-0c1b-11e8-8bac-0a11e521be98.png)
![ekran resmi 2018-02-07 15 23 57](https://user-images.githubusercontent.com/5227869/35916301-024bc5ae-0c1b-11e8-8985-a762b8bcacd6.png)
![ekran resmi 2018-02-07 15 23 46](https://user-images.githubusercontent.com/5227869/35916302-02717fba-0c1b-11e8-9c9b-1494989d3277.png)

**Comment by AlicanAkkus** [comment]
Merhabalar,

Item Approval özelliği Pazaryeri çözümünü kullanan merchantlar için kullanılabilirdir.
Pazaryeri çözümü için şuradan teknik destek alabilirsiniz -> **https://dev.iyzipay.com/tr/pazaryeri**

Diğer entegrasyon ve buna benzer durumlar için **entegrasyon@iyzico.com** adresine mail atabilirsiniz.
