### ISSUE TITLE
CheckoutForm'da Başarılı Ödemelerde PaymentStatus FAILURE Olarak Geliyor

### ISSUE THREAD

**Issue by emrealtann** [iyzico/iyzipay-dotnet#85]
Ödeme alınmasına rağmen ilgili CheckoutForm Response değerlerinde status FAILURE olarak geliyor.

**Comment by AyhanSahin** [comment]
aynı sorun bendede var.

**Comment by ShopskaSalad** [comment]
Konu sürdürülmediği için kapatılmıştır.
