### ISSUE TITLE
Hayatımda gördüğüm ender dandiklik seviyesinde bir API

### ISSUE THREAD

**Issue by havniyalcin** [iyzico/iyzipay-dotnet#86]
Verdiğiniz örnek ve dökümantasyon tam bir fiyasko.
Teşekkürler tembelliğiniz için!!!

**Comment by senerakdemir** [comment]
Vallahi katılmamak elde değil.
O kadar API kullandım (Garanti,Akbank,Finansbank,Twitter,Facebook,PayPal,PayU,Instagram ...) böylesine denk gelmedim.
Şayet benim gibi , iyzipay-dotnet projesinden bağımsız, temiz baştan kendinize göre Restfull servisini kullanarak yapmayı düşünüyorsanız aşağıda yazdıklarımı ve bağlantıları takip edebilirsiniz.

Öncelikle iyzico'nun şu beta sayfasını karıştırmakta fayda var :
[https://dev-beta.iyzipay.com/tr/tarifler/kendi-odeme-formunuz](url)

POSTMAN programı ile hangi URL'e GET,POST yapıldığını görebilirsiniz. Şuradan indirebilirsiniz :
[https://www.getpostman.com/](url) 

Programı indirip kayıt olduktan sonra :
[https://www.getpostman.com/collections/e883cd2eb09bf55cb1ff](url)
adresindeki js kodlarını indirip POSTMAN programına import ediyorsunuz. Ve karşınıza 9 hazır request geliyor. Bunları direk çalıştırıp ya da parametreleri değiştirip sonuçları görebilirsiniz. 
Authorization işlemi için neler gerekiyorsa hepsi bu programla görülebilir.
Tabi bu bazıları için samanlıkta iğne aramaya dönüşebilir.
Kolay gelsin :)

**Comment by bsglm** [comment]
+1

**Comment by ebicoglu** [comment]
+1
