### ISSUE TITLE
Authorization sorunu

### ISSUE THREAD

**Issue by senerakdemir** [iyzico/iyzipay-dotnet#87]
Merhabalar
iyzipay-dotnet kütüphanesi alternatifi yeni bir kütüphane yapıyorum. Taksit sorgulama için aşağıdaki bilgileri post ediyorum. Bu da giden header bilgileri :

**HEADERS**
POST https://sandbox-api.iyzipay.com/payment/iyzipos/installment
Authorization: IYZWS sandbox-afXhZPW0MQlE4dCUUlHcEopnMBgXnAZI:KGS7m4CDQA40g6r7zjRK+RaDOwM=
x-iyzi-rnd: 270420191009585715
Accept: application/json
Content-Type: application/json; charset=utf-8
Host: sandbox-api.iyzipay.com
Content-Length: 98
Expect: 100-continue

{"binNumber":"554960","price":"100.0","locale":"tr","conversationId":"123456789","currency":"TRY"}

**SORUN**
Authorization için kullandığım PKI string bu dizilimde olunca taksitleri veriyor :
[locale=tr,conversationId=123456789,binNumber=554960,price=100.0,currency=TRY]

Bu dizilimde gidince yani key sırası değişince :
[binNumber=554960,price=100.0,locale=tr,conversationId=123456789,currency=TRY]

api'nin yanıtı şu şekilde oluyor :
{"status":"failure","errorCode":"1000","errorMessage":"Geçersiz imza","locale":"tr","systemTime":1556392201687,"conversationId":"123456789"}

sorun nerede acaba?

**Comment by ShopskaSalad** [comment]
Selamlar,

Postman örnek sorgu referans alınabilir.
![image](https://user-images.githubusercontent.com/13609808/102082669-65f0f600-3e23-11eb-83e4-549bfd529ca2.png)

Kolaylıklar

**Comment by ShopskaSalad** [comment]
URL: https://api.iyzipay.com/payment/bin/check

> Selamlar,
> 
> Postman örnek sorgu referans alınabilir.
> ![image](https://user-images.githubusercontent.com/13609808/102082669-65f0f600-3e23-11eb-83e4-549bfd529ca2.png)
> 
> Kolaylıklar

URL Path:https://api.iyzipay.com/payment/bin/check

**Comment by ShopskaSalad** [comment]
Issue, cevap alınamadığı için kapatılmıştır.
