### ISSUE TITLE
Sürüm açıklamaları yok

### ISSUE THREAD

**Issue by ibrahimozgon** [iyzico/iyzipay-dotnet#99]
Canlıda kullandığımız eski sürümümüzde bir async-await problemi yasıyoruz. Çok kısa bir süre önce yeni bir versyion cıkmıssınız ancak versiyonlarınızda hic bir sürüm notu yok. Gözümüzü baglayıp son sürüme gecmek istemiyoruz. Sürüm notları paylasmayı düşünüyor musunuz ya da paylastıgınız ve bizim goruntuleyebileceğimiz bir adres var mıdır?

**Comment by halitsoydemir** [comment]
[RELEASE v2.1.33](https://github.com/iyzico/iyzipay-dotnet/releases/tag/v2.1.33)
[RELEASE v2.1.37](https://github.com/iyzico/iyzipay-dotnet/releases/tag/v2.1.37)

Releaseleri üzerine kısa açıklamalar eklendi
